# Generated by Django 4.2.16 on 2025-06-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_complex_contract_control_employer_event_zone_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='based_fk',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='zone',
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event_id'], name='based_fk'),
        ),
    ]
